name: Build layout
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download MSKLC
        run: |
          curl -L -o MSKLC.exe https://download.microsoft.com/download/6/f/5/6f5ce43a-e892-4fd1-b9a6-1a0cbb64e6e2/MSKLC.exe
      - name: Unzip MSKLC
        run: |
          ./MSKLC.exe -o . -y
      - name: Install MSKLC
        run: |
          MSKLC/MSKLC.msi /quiet TARGETDIR="./MSKLC-Install"
      - name: Build layout to C
        run: |
          cp multilingual.klc Target
          MSKLC-Install/bin/i386/kbdutool.exe -wus Target/multilin.klc
          del Target/multilin.klc
      - name: Upload C source
        uses: actions/upload-artifact@v4
        with:
          name: Compiled C source
          path: Target
      - name: Build layout DLL
        run: |
          MSKLC-Install/bin/i386/kbdutool.exe -wu multilingual.klc
      - name: Upload layout DLL
        uses: actions/upload-artifact@v4
        with:
          name: Compiled layout DLL
          path: multilingual.dll
